// src/components/KycCorporate.tsx
import React, { useState, useEffect, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import client from '../api/client';
import { useConfirmationDialog } from '../context/ConfirmationDialogContext';
import FormPageLayout from './layout/FormPageLayout';
import { StepClientDetails } from './kyc-corporate/StepClientDetails';
import { StepContactDetails } from './kyc-corporate/StepContactDetails';
import { StepSupportingDocuments } from './kyc-corporate/StepSupportingDocuments';
import { StepDeclaration } from './kyc-corporate/StepDeclaration';
import { CorporateFormData, FileSelections, FileInputRefs, STEPS, REQUIRED_FIELDS } from './kyc-corporate/types';
import SuccessModal from './ui/SuccessModal';
import { defaultToastrOptions, sanitizeErrorMessage } from '../lib/security';

declare const toastr: any;

const KycCorporate: React.FC = () => {
  const navigate = useNavigate();
  const { confirm } = useConfirmationDialog();
  const [activeStep, setActiveStep] = useState(0);
  const [loading, setLoading] = useState(false);
  const [errors, setErrors] = useState<{ [key: string]: string }>({});
  const [validationError, setValidationError] = useState<string>('');
  const [validationErrorStep, setValidationErrorStep] = useState<number | undefined>(undefined);
  const [showSuccessModal, setShowSuccessModal] = useState(false);

  useEffect(() => {
    if (typeof toastr !== 'undefined') {
      toastr.options = defaultToastrOptions;
    }
  }, []);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      const target = e.target as HTMLElement;
      if (target.tagName === 'INPUT' || target.tagName === 'TEXTAREA' || target.tagName === 'SELECT') {
        return;
      }
      if (e.key === 'ArrowRight') {
        setActiveStep((prev) => Math.min(STEPS.length - 1, prev + 1));
      } else if (e.key === 'ArrowLeft') {
        setActiveStep((prev) => Math.max(0, prev - 1));
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, []);

  const fileInputRefs: FileInputRefs = {
    identification: useRef<HTMLInputElement | null>(null),
    addressProof: useRef<HTMLInputElement | null>(null),
    articles: useRef<HTMLInputElement | null>(null),
    directorsId: useRef<HTMLInputElement | null>(null),
    sourceOfFunds: useRef<HTMLInputElement | null>(null),
    bankAccount: useRef<HTMLInputElement | null>(null),
  };

  const [fileSelections, setFileSelections] = useState<FileSelections>({
    identification: null,
    addressProof: null,
    articles: null,
    directorsId: null,
    sourceOfFunds: null,
    bankAccount: null,
  });

  const [formData, setFormData] = useState<CorporateFormData>({
    organizationName: '',
    products: [],
    schemeNumbers: [],
    phone: '',
    email: '',
    address: '',
    identificationDocument: '',
    contactPersonName: '',
    contactPersonPhone: '',
    contactPersonEmail: '',
    addressProof: '',
    articlesOfAssociation: '',
    directorsId: '',
    sourceOfFunds: '',
    bankAccountProof: '',
    pepDeclaration: false,
    declaration: false,
    documents: {
      identification: null,
      addressProof: null,
      articles: null,
      directorsId: null,
      sourceOfFunds: null,
      bankAccount: null,
    },
  });

  const handleInputChange = (field: keyof CorporateFormData, value: any) => {
    setFormData((prev) => ({ ...prev, [field]: value }));

    if (field === 'phone' || field === 'contactPersonPhone') {
      const phoneRegex = /^(09|08)\d{8}$/;
      if (value && !phoneRegex.test(value)) {
        setErrors((prev) => ({
          ...prev,
          [field]: 'Phone number must start with 09 or 08 and be exactly 10 digits',
        }));
      } else {
        setErrors((prev) => ({ ...prev, [field]: '' }));
      }
    }

    if (field === 'contactPersonEmail') {
      if (value && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)) {
        setErrors((prev) => ({ ...prev, contactPersonEmail: 'Please enter a valid email address' }));
      } else {
        setErrors((prev) => ({ ...prev, contactPersonEmail: '' }));
      }
    }
  };

  const handleProductChange = (product: string, checked: boolean) => {
    setFormData((prev) => ({
      ...prev,
      products: checked
        ? [...prev.products, product]
        : prev.products.filter((p) => p !== product),
    }));
  };

  const handleFileChange = (field: string, files: FileList | null) => {
    const file = files?.[0] || null;
    const fieldErrorMap: { [key: string]: string } = {
      'documents.identification': 'identificationFile',
      'documents.addressProof': 'addressProofFile',
      'documents.articles': 'articlesFile',
      'documents.directorsId': 'directorsIdFile',
      'documents.sourceOfFunds': 'sourceOfFundsFile',
      'documents.bankAccount': 'bankAccountFile',
    };
    const errorKey = fieldErrorMap[field];

    if (field.includes('.')) {
      const [parent, child] = field.split('.');
      setFormData((prev) => ({
        ...prev,
        [parent]: { ...(prev[parent as keyof CorporateFormData] as any), [child]: file },
      }));
      setFileSelections((prev) => ({ ...prev, [child]: file }));

      if (errorKey && file) {
        setErrors((prev) => ({ ...prev, [errorKey]: '' }));
      }
    } else {
      setFormData((prev) => ({ ...prev, [field]: file }));
      setFileSelections((prev) => ({ ...prev, [field]: file }));

      if (errorKey && file) {
        setErrors((prev) => ({ ...prev, [errorKey]: '' }));
      }
    }
  };

  const addSchemeNumber = () => {
    setFormData((prev) => ({
      ...prev,
      schemeNumbers: [...prev.schemeNumbers, ''],
    }));
  };

  const updateSchemeNumber = (index: number, value: string) => {
    setFormData((prev) => ({
      ...prev,
      schemeNumbers: prev.schemeNumbers.map((scheme, i) =>
        i === index ? value : scheme
      ),
    }));
  };

  const removeSchemeNumber = (index: number) => {
    setFormData((prev) => ({
      ...prev,
      schemeNumbers: prev.schemeNumbers.filter((_, i) => i !== index),
    }));
  };

  const validateForm = (): { valid: boolean; errorKeys: string[] } => {
    const newErrors: { [key: string]: string } = {};

    const checkField = (field: string) => {
      const value = formData[field as keyof CorporateFormData];
      if (typeof value === 'string') {
        if (!value.trim()) newErrors[field] = REQUIRED_FIELDS[field];
      } else if (Array.isArray(value)) {
        if (value.length === 0) newErrors[field] = REQUIRED_FIELDS[field];
      } else if (typeof value === 'boolean') {
        if (!value) newErrors[field] = REQUIRED_FIELDS[field];
      } else {
        if (!value) newErrors[field] = REQUIRED_FIELDS[field];
      }
    };

    for (const field of Object.keys(REQUIRED_FIELDS)) {
      if (field === 'declaration' || field === 'products' || field === 'schemeNumbers') {
        checkField(field);
      } else if (field.endsWith('File')) {
        const docField = field.replace('File', '');
        const docKey = docField === 'identification' ? 'documents.identification'
          : docField === 'addressProof' ? 'documents.addressProof'
          : docField === 'articles' ? 'documents.articles'
          : docField === 'directorsId' ? 'documents.directorsId'
          : docField === 'sourceOfFunds' ? 'documents.sourceOfFunds'
          : docField === 'bankAccount' ? 'documents.bankAccount'
          : null;
        if (docKey) {
          const [parent, child] = docKey.split('.');
          const docs = formData[parent as keyof CorporateFormData] as any;
          if (!docs?.[child]) newErrors[field] = REQUIRED_FIELDS[field];
        }
      } else {
        checkField(field);
      }
    }

    const phoneRegex = /^(09|08)\d{8}$/;
    if (formData.phone && !phoneRegex.test(formData.phone)) {
      newErrors.phone = 'Phone number must start with 09 or 08 and be exactly 10 digits';
    }
    if (formData.contactPersonPhone && !phoneRegex.test(formData.contactPersonPhone)) {
      newErrors.contactPersonPhone = 'Phone number must start with 09 or 08 and be exactly 10 digits';
    }

    if (formData.contactPersonEmail && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData.contactPersonEmail)) {
      newErrors.contactPersonEmail = 'Please enter a valid email address';
    }

    setErrors(newErrors);
    const errorKeys = Object.keys(newErrors);
    return { valid: errorKeys.length === 0, errorKeys };
  };

  const getFirstErrorStep = (errorKeys: string[]): number => {
    const step0Fields = ['organizationName', 'products', 'schemeNumbers', 'identificationDocument', 'identificationFile'];
    const step1Fields = ['phone', 'address', 'contactPersonName', 'contactPersonPhone', 'contactPersonEmail', 'addressProof', 'addressProofFile'];
    const step2Fields = ['articlesOfAssociation', 'articlesFile', 'directorsId', 'directorsIdFile', 'sourceOfFunds', 'sourceOfFundsFile', 'bankAccountProof', 'bankAccountFile'];
    const step3Fields = ['declaration'];

    for (const key of errorKeys) {
      if (step0Fields.includes(key)) return 0;
      if (step1Fields.includes(key)) return 1;
      if (step2Fields.includes(key)) return 2;
      if (step3Fields.includes(key)) return 3;
    }
    return 0;
  };

  const handleSubmit = async () => {
    const { valid, errorKeys } = validateForm();
    if (!valid) {
      const firstErrorStep = getFirstErrorStep(errorKeys);
      setValidationError('Please complete the required fields');
      setValidationErrorStep(firstErrorStep);
      setActiveStep(firstErrorStep);
      setLoading(false);
      return;
    }

    setValidationError('');
    setValidationErrorStep(undefined);

    const confirmed = await confirm({
      title: 'Submit corporate KYC?',
      message: 'This will submit the completed corporate KYC form and supporting documents for review.',
      confirmLabel: 'Submit KYC',
      tone: 'primary',
    });

    if (!confirmed) {
      return;
    }

    setLoading(true);
    try {
      const submitData = new FormData();
      submitData.append('type', 'corporate');
      submitData.append('clientName', formData.organizationName);
      submitData.append(
        'formData',
        JSON.stringify({
          organizationName: formData.organizationName,
          products: formData.products,
          schemeNumbers: formData.schemeNumbers.filter((scheme) => scheme.trim() !== ''),
          phone: formData.phone,
          email: formData.email,
          address: formData.address,
          identificationDocument: formData.identificationDocument,
          contactPerson: {
            name: formData.contactPersonName,
            phone: formData.contactPersonPhone,
            email: formData.contactPersonEmail,
          },
          addressProof: formData.addressProof,
          articlesOfAssociation: formData.articlesOfAssociation,
          directorsId: formData.directorsId,
          sourceOfFunds: formData.sourceOfFunds,
          bankAccountProof: formData.bankAccountProof,
          pepDeclaration: formData.pepDeclaration,
          declaration: formData.declaration,
        })
      );

      Object.entries(formData.documents).forEach(([key, file]) => {
        if (file) {
          submitData.append(key, file);
        }
      });

      await client.post('/api/kyc/submit', submitData, {
        headers: { 'Content-Type': 'multipart/form-data' },
      });

      setShowSuccessModal(true);
    } catch (error: any) {
      console.error('Submission error:', error?.response?.data || error);
      const rawMessage = error?.response?.data?.message || 'Failed to submit KYC. Please check your connection and try again.';
      const errorMessage = sanitizeErrorMessage(rawMessage);

      if (typeof toastr !== 'undefined') {
        toastr.error(errorMessage, 'Submission Failed');
      }
    }
    setLoading(false);
  };

  const isStepValid = (step: number): boolean => {
    if (step === 0) {
      return (
        !!formData.organizationName.trim() &&
        formData.products.length > 0 &&
        formData.schemeNumbers.filter((s) => s.trim()).length > 0 &&
        !!formData.identificationDocument &&
        !!formData.documents.identification
      );
    }
    if (step === 1) {
      return (
        !!formData.phone.trim() &&
        !!formData.address.trim() &&
        !!formData.contactPersonName.trim() &&
        !!formData.contactPersonPhone.trim() &&
        !!formData.contactPersonEmail.trim() &&
        !!formData.addressProof &&
        !!formData.documents.addressProof
      );
    }
    if (step === 2) {
      return (
        !!formData.articlesOfAssociation &&
        !!formData.documents.articles &&
        !!formData.directorsId &&
        !!formData.documents.directorsId &&
        !!formData.sourceOfFunds &&
        !!formData.documents.sourceOfFunds &&
        !!formData.bankAccountProof &&
        !!formData.documents.bankAccount
      );
    }
    if (step === 3) {
      return formData.declaration === true;
    }
    return true;
  };

  const handleNext = () => {
    setActiveStep((prev) => prev + 1);
  };

  const handlePrevious = () => {
    setActiveStep((prev) => Math.max(0, prev - 1));
  };

  const renderStepContent = (step: number) => {
    const stepProps = {
      formData,
      errors,
      fileSelections,
      fileInputRefs,
      handleInputChange,
      handleFileChange,
    };

    switch (step) {
      case 0:
        return (
          <StepClientDetails
            {...stepProps}
            handleProductChange={handleProductChange}
            addSchemeNumber={addSchemeNumber}
            updateSchemeNumber={updateSchemeNumber}
            removeSchemeNumber={removeSchemeNumber}
          />
        );
      case 1:
        return <StepContactDetails {...stepProps} />;
      case 2:
        return <StepSupportingDocuments {...stepProps} />;
      case 3:
        return <StepDeclaration {...stepProps} />;
      default:
        return (
          <div className="text-center py-12 text-gray-400">
            <p>Step {step + 1} coming soon...</p>
          </div>
        );
    }
  };

  return (
    <>
      <FormPageLayout
        title={STEPS[activeStep].label}
        activeStep={activeStep}
        totalSteps={STEPS.length}
        stepLabels={STEPS.map((s) => s.label)}
        onPrevious={handlePrevious}
        onNext={handleNext}
        onSubmit={handleSubmit}
        isLastStep={activeStep === STEPS.length - 1}
        isSubmitting={loading}
        nextDisabled={!isStepValid(activeStep)}
        validationError={validationError}
        validationErrorStep={validationErrorStep}
        validationErrorStepLabel={validationErrorStep !== undefined ? STEPS[validationErrorStep].label : undefined}
        onGoToStep={(step) => setActiveStep(step)}
        onDismissError={() => {
          setValidationError('');
          setValidationErrorStep(undefined);
        }}
      >
        {renderStepContent(activeStep)}
      </FormPageLayout>
      <SuccessModal
        open={showSuccessModal}
        message="Your Corporate KYC has been submitted successfully!"
        onClose={() => {
          setShowSuccessModal(false);
          navigate('/');
        }}
      />
    </>
  );
};

export default KycCorporate;

// src/views/KycCorporate.vue
<script setup lang="ts">
import { onMounted, onUnmounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import client from '@/api/client'
import { useConfirm } from '@/composables/useConfirm'
import { useToast } from '@/composables/useToast'
import { sanitizeErrorMessage } from '@/lib/security'
import FormPageLayout from '@/layouts/FormPageLayout.vue'
import SuccessModal from '@/components/ui/SuccessModal.vue'
import StepClientDetails from '@/components/kyc-corporate/StepClientDetails.vue'
import StepContactDetails from '@/components/kyc-corporate/StepContactDetails.vue'
import StepSupportingDocuments from '@/components/kyc-corporate/StepSupportingDocuments.vue'
import StepDeclaration from '@/components/kyc-corporate/StepDeclaration.vue'
import {
  STEPS,
  REQUIRED_FIELDS,
  type CorporateFormData,
  type FileSelections,
} from '@/components/kyc-corporate/interfaces'

const router = useRouter()
const { confirm } = useConfirm()
const toast = useToast()

const activeStep = ref(0)
const loading = ref(false)
const errors = ref<Record<string, string>>({})
const validationError = ref('')
const validationErrorStep = ref<number | undefined>(undefined)
const showSuccessModal = ref(false)

function handleKeyDown(e: KeyboardEvent) {
  const target = e.target as HTMLElement
  if (target.tagName === 'INPUT' || target.tagName === 'TEXTAREA' || target.tagName === 'SELECT') {
    return
  }
  if (e.key === 'ArrowRight') {
    activeStep.value = Math.min(STEPS.length - 1, activeStep.value + 1)
  } else if (e.key === 'ArrowLeft') {
    activeStep.value = Math.max(0, activeStep.value - 1)
  }
}

onMounted(() => window.addEventListener('keydown', handleKeyDown))
onUnmounted(() => window.removeEventListener('keydown', handleKeyDown))

const fileSelections = ref<FileSelections>({
  identification: null,
  addressProof: null,
  articles: null,
  directorsId: null,
  sourceOfFunds: null,
  bankAccount: null,
})

const formData = reactive<CorporateFormData>({
  organizationName: '',
  products: [],
  schemeNumbers: [],
  phone: '',
  email: '',
  address: '',
  identificationDocument: '',
  contactPersonName: '',
  contactPersonPhone: '',
  contactPersonEmail: '',
  addressProof: '',
  articlesOfAssociation: '',
  directorsId: '',
  sourceOfFunds: '',
  bankAccountProof: '',
  pepDeclaration: false,
  declaration: false,
  documents: {
    identification: null,
    addressProof: null,
    articles: null,
    directorsId: null,
    sourceOfFunds: null,
    bankAccount: null,
  },
})

function handleInputChange(field: keyof CorporateFormData, value: any) {
  ;(formData as any)[field] = value

  if (field === 'phone' || field === 'contactPersonPhone') {
    const phoneRegex = /^(09|08)\d{8}$/
    if (value && !phoneRegex.test(value)) {
      errors.value = {
        ...errors.value,
        [field]: 'Phone number must start with 09 or 08 and be exactly 10 digits',
      }
    } else {
      errors.value = { ...errors.value, [field]: '' }
    }
  }

  if (field === 'contactPersonEmail') {
    if (value && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)) {
      errors.value = {
        ...errors.value,
        contactPersonEmail: 'Please enter a valid email address',
      }
    } else {
      errors.value = { ...errors.value, contactPersonEmail: '' }
    }
  }
}

function handleProductChange(product: string, checked: boolean) {
  formData.products = checked
    ? [...formData.products, product]
    : formData.products.filter((p) => p !== product)
}

function handleFileChange(field: string, files: FileList | null) {
  const file = files?.[0] || null
  const fieldErrorMap: Record<string, string> = {
    'documents.identification': 'identificationFile',
    'documents.addressProof': 'addressProofFile',
    'documents.articles': 'articlesFile',
    'documents.directorsId': 'directorsIdFile',
    'documents.sourceOfFunds': 'sourceOfFundsFile',
    'documents.bankAccount': 'bankAccountFile',
  }
  const errorKey = fieldErrorMap[field]

  if (field.includes('.')) {
    const [parent, child] = field.split('.')
    const docs = formData[parent as 'documents'] as unknown as Record<string, File | null>
    docs[child] = file
    fileSelections.value = { ...fileSelections.value, [child]: file }

    if (errorKey && file) {
      errors.value = { ...errors.value, [errorKey]: '' }
    }
  } else {
    ;(formData as any)[field] = file
    fileSelections.value = { ...fileSelections.value, [field]: file }

    if (errorKey && file) {
      errors.value = { ...errors.value, [errorKey]: '' }
    }
  }
}

function addSchemeNumber() {
  formData.schemeNumbers = [...formData.schemeNumbers, '']
}

function updateSchemeNumber(index: number, value: string) {
  formData.schemeNumbers = formData.schemeNumbers.map((scheme, i) =>
    i === index ? value : scheme,
  )
}

function removeSchemeNumber(index: number) {
  formData.schemeNumbers = formData.schemeNumbers.filter((_, i) => i !== index)
}

function validateForm(): { valid: boolean; errorKeys: string[] } {
  const newErrors: Record<string, string> = {}

  const checkField = (field: string) => {
    const value = (formData as unknown as Record<string, unknown>)[field]
    if (typeof value === 'string') {
      if (!value.trim()) newErrors[field] = REQUIRED_FIELDS[field]
    } else if (Array.isArray(value)) {
      if (value.length === 0) newErrors[field] = REQUIRED_FIELDS[field]
    } else if (typeof value === 'boolean') {
      if (!value) newErrors[field] = REQUIRED_FIELDS[field]
    } else {
      if (!value) newErrors[field] = REQUIRED_FIELDS[field]
    }
  }

  for (const field of Object.keys(REQUIRED_FIELDS)) {
    if (field === 'declaration' || field === 'products' || field === 'schemeNumbers') {
      checkField(field)
    } else if (field.endsWith('File')) {
      const docField = field.replace('File', '')
      const docKey = docField === 'identification' ? 'documents.identification'
        : docField === 'addressProof' ? 'documents.addressProof'
        : docField === 'articles' ? 'documents.articles'
        : docField === 'directorsId' ? 'documents.directorsId'
        : docField === 'sourceOfFunds' ? 'documents.sourceOfFunds'
        : docField === 'bankAccount' ? 'documents.bankAccount'
        : null
      if (docKey) {
        const [parent, child] = docKey.split('.')
        const docs = (formData as unknown as Record<string, any>)[parent]
        if (!docs?.[child]) newErrors[field] = REQUIRED_FIELDS[field]
      }
    } else {
      checkField(field)
    }
  }

  const phoneRegex = /^(09|08)\d{8}$/
  if (formData.phone && !phoneRegex.test(formData.phone)) {
    newErrors.phone = 'Phone number must start with 09 or 08 and be exactly 10 digits'
  }
  if (formData.contactPersonPhone && !phoneRegex.test(formData.contactPersonPhone)) {
    newErrors.contactPersonPhone = 'Phone number must start with 09 or 08 and be exactly 10 digits'
  }

  if (formData.contactPersonEmail && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData.contactPersonEmail)) {
    newErrors.contactPersonEmail = 'Please enter a valid email address'
  }

  errors.value = newErrors
  const errorKeys = Object.keys(newErrors)
  return { valid: errorKeys.length === 0, errorKeys }
}

function getFirstErrorStep(errorKeys: string[]): number {
  const step0Fields = ['organizationName', 'products', 'schemeNumbers', 'identificationDocument', 'identificationFile']
  const step1Fields = ['phone', 'address', 'contactPersonName', 'contactPersonPhone', 'contactPersonEmail', 'addressProof', 'addressProofFile']
  const step2Fields = ['articlesOfAssociation', 'articlesFile', 'directorsId', 'directorsIdFile', 'sourceOfFunds', 'sourceOfFundsFile', 'bankAccountProof', 'bankAccountFile']
  const step3Fields = ['declaration']

  for (const key of errorKeys) {
    if (step0Fields.includes(key)) return 0
    if (step1Fields.includes(key)) return 1
    if (step2Fields.includes(key)) return 2
    if (step3Fields.includes(key)) return 3
  }
  return 0
}

async function handleSubmit() {
  const { valid, errorKeys } = validateForm()
  if (!valid) {
    const firstErrorStep = getFirstErrorStep(errorKeys)
    validationError.value = 'Please complete the required fields'
    validationErrorStep.value = firstErrorStep
    activeStep.value = firstErrorStep
    loading.value = false
    return
  }

  validationError.value = ''
  validationErrorStep.value = undefined

  const confirmed = await confirm({
    title: 'Submit corporate KYC?',
    message: 'This will submit the completed corporate KYC form and supporting documents for review.',
    confirmLabel: 'Submit KYC',
    tone: 'primary',
  })

  if (!confirmed) {
    return
  }

  loading.value = true
  try {
    const submitData = new FormData()
    submitData.append('type', 'corporate')
    submitData.append('clientName', formData.organizationName)
    submitData.append(
      'formData',
      JSON.stringify({
        organizationName: formData.organizationName,
        products: formData.products,
        schemeNumbers: formData.schemeNumbers.filter((scheme) => scheme.trim() !== ''),
        phone: formData.phone,
        email: formData.email,
        address: formData.address,
        identificationDocument: formData.identificationDocument,
        contactPerson: {
          name: formData.contactPersonName,
          phone: formData.contactPersonPhone,
          email: formData.contactPersonEmail,
        },
        addressProof: formData.addressProof,
        articlesOfAssociation: formData.articlesOfAssociation,
        directorsId: formData.directorsId,
        sourceOfFunds: formData.sourceOfFunds,
        bankAccountProof: formData.bankAccountProof,
        pepDeclaration: formData.pepDeclaration,
        declaration: formData.declaration,
      }),
    )

    Object.entries(formData.documents).forEach(([key, file]) => {
      if (file) {
        submitData.append(key, file)
      }
    })

    await client.post('/api/kyc/submit', submitData, {
      headers: { 'Content-Type': 'multipart/form-data' },
    })

    showSuccessModal.value = true
  } catch (error: any) {
    console.error('Submission error:', error?.response?.data || error)
    const rawMessage = error?.response?.data?.message || 'Failed to submit KYC. Please check your connection and try again.'
    const errorMessage = sanitizeErrorMessage(rawMessage)

    toast.error(errorMessage, 'Submission Failed')
  }
  loading.value = false
}

function isStepValid(step: number): boolean {
  if (step === 0) {
    return (
      !!formData.organizationName.trim() &&
      formData.products.length > 0 &&
      formData.schemeNumbers.filter((s) => s.trim()).length > 0 &&
      !!formData.identificationDocument &&
      !!formData.documents.identification
    )
  }
  if (step === 1) {
    return (
      !!formData.phone.trim() &&
      !!formData.address.trim() &&
      !!formData.contactPersonName.trim() &&
      !!formData.contactPersonPhone.trim() &&
      !!formData.contactPersonEmail.trim() &&
      !!formData.addressProof &&
      !!formData.documents.addressProof
    )
  }
  if (step === 2) {
    return (
      !!formData.articlesOfAssociation &&
      !!formData.documents.articles &&
      !!formData.directorsId &&
      !!formData.documents.directorsId &&
      !!formData.sourceOfFunds &&
      !!formData.documents.sourceOfFunds &&
      !!formData.bankAccountProof &&
      !!formData.documents.bankAccount
    )
  }
  if (step === 3) {
    return formData.declaration === true
  }
  return true
}

function handleNext() {
  activeStep.value = activeStep.value + 1
}

function handlePrevious() {
  activeStep.value = Math.max(0, activeStep.value - 1)
}

function handleDismissError() {
  validationError.value = ''
  validationErrorStep.value = undefined
}

function handleSuccessClose() {
  showSuccessModal.value = false
  router.push('/')
}
</script>

<template>
  <FormPageLayout
    :title="STEPS[activeStep].label"
    :active-step="activeStep"
    :total-steps="STEPS.length"
    :step-labels="STEPS.map((s) => s.label)"
    :is-last-step="activeStep === STEPS.length - 1"
    :is-submitting="loading"
    :next-disabled="!isStepValid(activeStep)"
    :validation-error="validationError"
    :validation-error-step="validationErrorStep"
    :validation-error-step-label="validationErrorStep !== undefined ? STEPS[validationErrorStep].label : undefined"
    @previous="handlePrevious"
    @next="handleNext"
    @submit="handleSubmit"
    @go-to-step="(step) => (activeStep = step)"
    @dismiss-error="handleDismissError"
  >
    <StepClientDetails
      v-if="activeStep === 0"
      :form-data="formData"
      :errors="errors"
      :file-selections="fileSelections"
      @input-change="handleInputChange"
      @file-change="handleFileChange"
      @product-change="handleProductChange"
      @add-scheme-number="addSchemeNumber"
      @update-scheme-number="updateSchemeNumber"
      @remove-scheme-number="removeSchemeNumber"
    />
    <StepContactDetails
      v-else-if="activeStep === 1"
      :form-data="formData"
      :errors="errors"
      :file-selections="fileSelections"
      @input-change="handleInputChange"
      @file-change="handleFileChange"
    />
    <StepSupportingDocuments
      v-else-if="activeStep === 2"
      :form-data="formData"
      :errors="errors"
      :file-selections="fileSelections"
      @input-change="handleInputChange"
      @file-change="handleFileChange"
    />
    <StepDeclaration
      v-else-if="activeStep === 3"
      :form-data="formData"
      :errors="errors"
      :file-selections="fileSelections"
      @input-change="handleInputChange"
    />
    <div v-else class="text-center py-12 text-gray-400">
      <p>Step {{ activeStep + 1 }} coming soon...</p>
    </div>
  </FormPageLayout>
  <SuccessModal
    :open="showSuccessModal"
    message="Your Corporate KYC has been submitted successfully!"
    @close="handleSuccessClose"
  />
</template>
