// src/components/kyc-individual/StepContact.vue
<script setup lang="ts">
import FloatingInput from '@/components/ui/FloatingInput.vue'
import FloatingSelect from '@/components/ui/FloatingSelect.vue'
import RadioGroup from '@/components/ui/RadioGroup.vue'
import RadioGroupItem from '@/components/ui/RadioGroupItem.vue'
import Label from '@/components/ui/Label.vue'
import SelectItem from '@/components/ui/SelectItem.vue'
import ErrorIcon from '@/components/kyc-group/ErrorIcon.vue'
import {
  RELATIONSHIPS,
  COMMUNICATION_OPTIONS,
  isRequired,
  requiredLabel,
} from './interfaces'
import type { IndividualFormData, StepProps } from './interfaces'

defineProps<StepProps>()

const emit = defineEmits<{
  inputChange: [field: keyof IndividualFormData, value: unknown]
}>()

function commOptionId(option: string): string {
  return `comm-${option.replace(/\s+/g, '-').toLowerCase()}`
}
</script>

<template>
  <div>
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-8">
      <div>
        <FloatingInput
          id="nextOfKinName"
          :label="requiredLabel('Name of Next of Kin', 'nextOfKinName')"
          :model-value="formData.nextOfKinName"
          :error="!!errors.nextOfKinName"
          :maxlength="100"
          @update:model-value="emit('inputChange', 'nextOfKinName', $event)"
        >
          <template #label>
            Name of Next of Kin
            <span v-if="isRequired('nextOfKinName')" class="text-om-error">*</span>
          </template>
        </FloatingInput>
        <div v-if="errors.nextOfKinName" class="flex items-center gap-1.5 mt-1">
          <ErrorIcon />
          <p class="text-xs text-om-error font-medium">{{ errors.nextOfKinName }}</p>
        </div>
      </div>
      <div>
        <FloatingSelect
          :label="requiredLabel('Relationship to Customer', 'nextOfKinRelationship')"
          :model-value="formData.nextOfKinRelationship"
          :error="!!errors.nextOfKinRelationship"
          @update:model-value="emit('inputChange', 'nextOfKinRelationship', $event ?? '')"
        >
          <template #label>
            Relationship to Customer
            <span v-if="isRequired('nextOfKinRelationship')" class="text-om-error">*</span>
          </template>
          <SelectItem v-for="relationship in RELATIONSHIPS" :key="relationship" :value="relationship">
            {{ relationship }}
          </SelectItem>
        </FloatingSelect>
        <div v-if="errors.nextOfKinRelationship" class="flex items-center gap-1.5 mt-1">
          <ErrorIcon />
          <p class="text-xs text-om-error font-medium">{{ errors.nextOfKinRelationship }}</p>
        </div>
      </div>
    </div>

    <div class="border-t border-gray-200 mb-8" />

    <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-8">
      <div>
        <FloatingInput
          id="nextOfKinOccupation"
          :label="requiredLabel('Occupation', 'nextOfKinOccupation')"
          :model-value="formData.nextOfKinOccupation"
          :error="!!errors.nextOfKinOccupation"
          :maxlength="100"
          @update:model-value="emit('inputChange', 'nextOfKinOccupation', $event)"
        >
          <template #label>
            Occupation
            <span v-if="isRequired('nextOfKinOccupation')" class="text-om-error">*</span>
          </template>
        </FloatingInput>
        <div v-if="errors.nextOfKinOccupation" class="flex items-center gap-1.5 mt-1">
          <ErrorIcon />
          <p class="text-xs text-om-error font-medium">{{ errors.nextOfKinOccupation }}</p>
        </div>
      </div>
      <div>
        <FloatingInput
          id="cellNumber"
          :label="requiredLabel('Mobile Number', 'cellNumber')"
          :model-value="formData.cellNumber"
          :error="!!errors.cellNumber"
          :maxlength="20"
          @update:model-value="emit('inputChange', 'cellNumber', $event)"
        >
          <template #label>
            Mobile Number
            <span v-if="isRequired('cellNumber')" class="text-om-error">*</span>
          </template>
        </FloatingInput>
        <div v-if="errors.cellNumber" class="flex items-center gap-1.5 mt-1">
          <ErrorIcon />
          <p class="text-xs text-om-error font-medium">{{ errors.cellNumber }}</p>
        </div>
      </div>
    </div>

    <div class="border-t border-gray-200 mb-8" />

    <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-8">
      <div>
        <FloatingInput
          id="mobileNumber"
          label="Telephone Number"
          :model-value="formData.mobileNumber"
          :maxlength="20"
          @update:model-value="emit('inputChange', 'mobileNumber', $event)"
        />
      </div>
      <div>
        <FloatingInput
          id="emailAddress"
          :label="requiredLabel('Email Address', 'emailAddress')"
          type="email"
          :model-value="formData.emailAddress"
          :error="!!errors.emailAddress"
          :maxlength="254"
          @update:model-value="emit('inputChange', 'emailAddress', $event)"
        >
          <template #label>
            Email Address
            <span v-if="isRequired('emailAddress')" class="text-om-error">*</span>
          </template>
        </FloatingInput>
        <div v-if="errors.emailAddress" class="flex items-center gap-1.5 mt-1">
          <ErrorIcon />
          <p class="text-xs text-om-error font-medium">{{ errors.emailAddress }}</p>
        </div>
      </div>
    </div>

    <div class="border-t border-gray-200 mb-8" />

    <div>
      <Label class="text-sm font-bold text-black mb-4 block">
        {{ requiredLabel('Preferred Mode of Communication', 'preferredCommunication') }}
        <span v-if="isRequired('preferredCommunication')" class="text-om-error">*</span>
      </Label>
      <RadioGroup
        :model-value="formData.preferredCommunication"
        class="flex flex-col gap-3"
        @update:model-value="emit('inputChange', 'preferredCommunication', $event)"
      >
        <div v-for="option in COMMUNICATION_OPTIONS" :key="option" class="flex items-center gap-3">
          <RadioGroupItem :id="commOptionId(option)" :value="option" />
          <Label :for="commOptionId(option)" class="cursor-pointer text-sm">
            {{ option }}
          </Label>
        </div>
      </RadioGroup>
      <div v-if="errors.preferredCommunication" class="flex items-center gap-1.5 mt-2">
        <ErrorIcon class="h-4 w-4 shrink-0" />
        <p class="text-sm text-om-error font-medium">{{ errors.preferredCommunication }}</p>
      </div>
    </div>
  </div>
</template>

// src/components/kyc-individual/StepContact.tsx
import React from 'react';
import { FloatingInput } from '../ui/floating-input';
import { FloatingSelect } from '../ui/floating-select';
import { SelectItem } from '../ui/select';
import { RadioGroup, RadioItem } from '../ui/radio';
import { Label } from '../ui/label';
import { ErrorIcon } from '../kyc-group/ErrorIcon';
import { StepProps, RELATIONSHIPS, COMMUNICATION_OPTIONS, requiredLabel } from './types';

export const StepContact: React.FC<StepProps> = ({
  formData,
  errors,
  handleInputChange,
}) => {
  return (
    <div>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-8">
        <div>
          <FloatingInput
            id="nextOfKinName"
            label={requiredLabel('Name of Next of Kin', 'nextOfKinName')}
            value={formData.nextOfKinName}
            onChange={(e) => handleInputChange('nextOfKinName', e.target.value)}
            error={!!errors.nextOfKinName}
            maxLength={100}
          />
          {errors.nextOfKinName && (
            <div className="flex items-center gap-1.5 mt-1">
              <ErrorIcon />
              <p className="text-xs text-om-error font-medium">{errors.nextOfKinName}</p>
            </div>
          )}
        </div>
        <div>
          <FloatingSelect
            label={requiredLabel('Relationship to Customer', 'nextOfKinRelationship')}
            value={formData.nextOfKinRelationship}
            onValueChange={(value: string) => handleInputChange('nextOfKinRelationship', value)}
            error={!!errors.nextOfKinRelationship}
          >
            {RELATIONSHIPS.map((relationship) => (
              <SelectItem key={relationship} value={relationship}>
                {relationship}
              </SelectItem>
            ))}
          </FloatingSelect>
          {errors.nextOfKinRelationship && (
            <div className="flex items-center gap-1.5 mt-1">
              <ErrorIcon />
              <p className="text-xs text-om-error font-medium">{errors.nextOfKinRelationship}</p>
            </div>
          )}
        </div>
      </div>

      <div className="border-t border-gray-200 mb-8" />

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-8">
        <div>
          <FloatingInput
            id="nextOfKinOccupation"
            label={requiredLabel('Occupation', 'nextOfKinOccupation')}
            value={formData.nextOfKinOccupation}
            onChange={(e) => handleInputChange('nextOfKinOccupation', e.target.value)}
            error={!!errors.nextOfKinOccupation}
            maxLength={100}
          />
          {errors.nextOfKinOccupation && (
            <div className="flex items-center gap-1.5 mt-1">
              <ErrorIcon />
              <p className="text-xs text-om-error font-medium">{errors.nextOfKinOccupation}</p>
            </div>
          )}
        </div>
        <div>
          <FloatingInput
            id="cellNumber"
            label={requiredLabel('Mobile Number', 'cellNumber')}
            value={formData.cellNumber}
            onChange={(e) => handleInputChange('cellNumber', e.target.value)}
            error={!!errors.cellNumber}
            maxLength={20}
          />
          {errors.cellNumber && (
            <div className="flex items-center gap-1.5 mt-1">
              <ErrorIcon />
              <p className="text-xs text-om-error font-medium">{errors.cellNumber}</p>
            </div>
          )}
        </div>
      </div>

      <div className="border-t border-gray-200 mb-8" />

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-8">
        <div>
          <FloatingInput
            id="mobileNumber"
            label="Telephone Number"
            value={formData.mobileNumber}
            onChange={(e) => handleInputChange('mobileNumber', e.target.value)}
            maxLength={20}
          />
        </div>
        <div>
          <FloatingInput
            id="emailAddress"
            label={requiredLabel('Email Address', 'emailAddress')}
            type="email"
            value={formData.emailAddress}
            onChange={(e) => handleInputChange('emailAddress', e.target.value)}
            error={!!errors.emailAddress}
            maxLength={254}
          />
          {errors.emailAddress && (
            <div className="flex items-center gap-1.5 mt-1">
              <ErrorIcon />
              <p className="text-xs text-om-error font-medium">{errors.emailAddress}</p>
            </div>
          )}
        </div>
      </div>

      <div className="border-t border-gray-200 mb-8" />

      <div>
        <Label className="text-sm font-bold text-black mb-4 block">
          {requiredLabel('Preferred Mode of Communication', 'preferredCommunication')}
        </Label>
        <RadioGroup
          value={formData.preferredCommunication}
          onValueChange={(value: string) => handleInputChange('preferredCommunication', value)}
          className="flex flex-col gap-3"
        >
          {COMMUNICATION_OPTIONS.map((option) => (
            <div key={option} className="flex items-center gap-3">
              <RadioItem id={`comm-${option.replace(/\s+/g, '-').toLowerCase()}`} value={option} />
              <Label
                htmlFor={`comm-${option.replace(/\s+/g, '-').toLowerCase()}`}
                className="cursor-pointer text-sm"
              >
                {option}
              </Label>
            </div>
          ))}
        </RadioGroup>
        {errors.preferredCommunication && (
          <div className="flex items-center gap-1.5 mt-2">
            <ErrorIcon className="h-4 w-4 shrink-0" />
            <p className="text-sm text-om-error font-medium">{errors.preferredCommunication}</p>
          </div>
        )}
      </div>
    </div>
  );
};
