// src/components/ui/FileUploadArea.tsx
import React, { useState, useEffect } from 'react';
import { FileText, Upload, Trash2, X } from 'lucide-react';

export interface FileSelections {
  [key: string]: File | null;
}

export interface FileInputRefs {
  [key: string]: React.RefObject<HTMLInputElement | null>;
}

interface FileUploadAreaProps {
  label: string;
  field: string;
  error?: string;
  fileSelections: FileSelections;
  fileInputRefs: FileInputRefs;
  handleFileChange: (field: string, files: FileList | null) => void;
  multiple?: boolean;
  maxSizeMB?: number;
}

const formatFileSize = (bytes?: number) => {
  if (!bytes) return '';
  const mb = bytes / (1024 * 1024);
  return mb < 1 ? `${Math.round(bytes / 1024)} KB` : `${mb.toFixed(2)} MB`;
};

export const FileUploadArea: React.FC<FileUploadAreaProps> = ({
  label,
  field,
  error,
  fileSelections,
  fileInputRefs,
  handleFileChange,
  multiple = false,
  maxSizeMB = 10,
}) => {
  const fileKey = field.split('.')[1] || field;
  const selectedFile = fileSelections[fileKey];
  const hasFile = Boolean(selectedFile);
  const [isUploading, setIsUploading] = useState(false);
  const [uploadProgress, setUploadProgress] = useState(0);
  const [prevFileName, setPrevFileName] = useState<string | null>(null);
  const [sizeError, setSizeError] = useState<string | null>(null);

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (files && files.length > 0) {
      const file = files[0];
      const maxBytes = maxSizeMB * 1024 * 1024;
      if (file.size > maxBytes) {
        setSizeError(`File size exceeds ${maxSizeMB} MB limit`);
        e.target.value = '';
        return;
      }
      setSizeError(null);
    } else {
      setSizeError(null);
    }
    handleFileChange(field, files);
  };

  useEffect(() => {
    const currentFileName = selectedFile?.name || null;
    if (currentFileName && currentFileName !== prevFileName) {
      setPrevFileName(currentFileName);
      setIsUploading(true);
      setUploadProgress(0);

      const duration = 1500;
      const interval = 30;
      const steps = duration / interval;
      const increment = 100 / steps;
      let progress = 0;

      const timer = setInterval(() => {
        progress += increment;
        if (progress >= 100) {
          progress = 100;
          clearInterval(timer);
          setTimeout(() => {
            setIsUploading(false);
            setUploadProgress(0);
          }, 200);
        }
        setUploadProgress(Math.min(progress, 100));
      }, interval);

      return () => clearInterval(timer);
    } else if (!currentFileName) {
      setPrevFileName(null);
      setIsUploading(false);
      setUploadProgress(0);
    }
    // prevFileName is the comparison baseline this effect updates; including it would re-run the animation.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedFile?.name]);

  const displayError = error || sizeError;
  const isSuccess = hasFile && !displayError && !isUploading;

  const handleRemove = (e: React.MouseEvent) => {
    e.stopPropagation();
    setSizeError(null);
    handleFileChange(field, null);
  };

  let containerClasses =
    'relative w-full overflow-hidden rounded-xl cursor-pointer flex items-center justify-between p-4 transition-all duration-200 ';

  if (displayError) {
    containerClasses += 'border-2 border-om-error bg-om-error/5';
  } else if (isSuccess) {
    containerClasses += 'border border-om-green bg-om-green/5';
  } else {
    containerClasses += 'border border-gray-300 bg-white hover:bg-gray-50 hover:border-om-green';
  }

  return (
    <div>
      <input
        ref={fileInputRefs[fileKey as keyof typeof fileInputRefs]}
        type="file"
        onChange={handleFileSelect}
        className="hidden"
        accept=".pdf,.png,.jpg,.jpeg"
        multiple={multiple}
      />

      <div
        onClick={() => fileInputRefs[fileKey as keyof typeof fileInputRefs]?.current?.click()}
        className={containerClasses}
      >
        <div className="flex items-center gap-3">
          <FileText
            className={`h-5 w-5 shrink-0 ${
              displayError ? 'text-om-error' : isSuccess ? 'text-om-green' : 'text-gray-500'
            }`}
          />
          <div>
            <p
              className={`text-sm font-medium ${
                hasFile ? 'text-gray-800' : 'text-gray-400'
              }`}
            >
              {selectedFile ? selectedFile.name : label}
            </p>

            {displayError ? (
              <p className="text-xs font-medium text-om-error">{displayError}</p>
            ) : isUploading ? (
              <p className="text-xs text-gray-400">Uploading...</p>
            ) : isSuccess ? (
              <p className="text-xs text-gray-400">{formatFileSize(selectedFile?.size)}</p>
            ) : (
              <p className="text-xs text-gray-400">PDF, PNG or JPG. Max {maxSizeMB} MB</p>
            )}
          </div>
        </div>

        {displayError ? (
          <X className="h-5 w-5 shrink-0 text-om-error" onClick={handleRemove} />
        ) : isUploading ? (
          <X className="h-5 w-5 shrink-0 text-gray-500" onClick={handleRemove} />
        ) : isSuccess ? (
          <Trash2 className="h-5 w-5 shrink-0 text-gray-500" onClick={handleRemove} />
        ) : (
          <Upload className="h-5 w-5 shrink-0 text-gray-500" />
        )}

        {isUploading && (
          <div className="absolute inset-x-0 bottom-0 h-1 bg-gray-100">
            <div
              className="h-full bg-om-green transition-all duration-300"
              style={{ width: `${uploadProgress}%` }}
            />
          </div>
        )}
      </div>
    </div>
  );
};

// src/components/ui/FileUploadArea.vue
<script setup lang="ts">
import { computed, onUnmounted, ref, watch } from 'vue'
import { FileText, Upload, Trash2, X } from '@lucide/vue'
import type { FileUploadAreaProps } from './types'

const props = withDefaults(defineProps<FileUploadAreaProps>(), {
  multiple: false,
  maxSizeMB: 10,
})

const emit = defineEmits<{
  fileChange: [field: string, files: FileList | null]
}>()

const fileInput = ref<HTMLInputElement | null>(null)

const fileKey = computed(() => props.field.split('.')[1] || props.field)
const selectedFile = computed(() => props.fileSelections[fileKey.value])
const hasFile = computed(() => Boolean(selectedFile.value))

const isUploading = ref(false)
const uploadProgress = ref(0)
const prevFileName = ref<string | null>(null)
const sizeError = ref<string | null>(null)

let progressTimer: ReturnType<typeof setInterval> | undefined
let doneTimer: ReturnType<typeof setTimeout> | undefined

function clearTimers() {
  if (progressTimer !== undefined) {
    clearInterval(progressTimer)
    progressTimer = undefined
  }
  if (doneTimer !== undefined) {
    clearTimeout(doneTimer)
    doneTimer = undefined
  }
}

function formatFileSize(bytes?: number) {
  if (!bytes) return ''
  const mb = bytes / (1024 * 1024)
  return mb < 1 ? `${Math.round(bytes / 1024)} KB` : `${mb.toFixed(2)} MB`
}

function handleFileSelect(event: Event) {
  const input = event.target as HTMLInputElement
  const files = input.files
  if (files && files.length > 0) {
    const file = files[0]
    const maxBytes = props.maxSizeMB * 1024 * 1024
    if (file.size > maxBytes) {
      sizeError.value = `File size exceeds ${props.maxSizeMB} MB limit`
      input.value = ''
      return
    }
    sizeError.value = null
  } else {
    sizeError.value = null
  }
  emit('fileChange', props.field, files)
}

watch(
  () => selectedFile.value?.name,
  (currentFileName) => {
    clearTimers()
    if (currentFileName && currentFileName !== prevFileName.value) {
      prevFileName.value = currentFileName
      isUploading.value = true
      uploadProgress.value = 0

      const duration = 1500
      const interval = 30
      const steps = duration / interval
      const increment = 100 / steps
      let progress = 0

      progressTimer = setInterval(() => {
        progress += increment
        if (progress >= 100) {
          progress = 100
          if (progressTimer !== undefined) {
            clearInterval(progressTimer)
            progressTimer = undefined
          }
          doneTimer = setTimeout(() => {
            isUploading.value = false
            uploadProgress.value = 0
          }, 200)
        }
        uploadProgress.value = Math.min(progress, 100)
      }, interval)
    } else if (!currentFileName) {
      prevFileName.value = null
      isUploading.value = false
      uploadProgress.value = 0
    }
  },
)

onUnmounted(clearTimers)

const displayError = computed(() => props.error || sizeError.value)
const isSuccess = computed(() => hasFile.value && !displayError.value && !isUploading.value)

const containerClasses = computed(() => {
  let classes =
    'relative w-full overflow-hidden rounded-xl cursor-pointer flex items-center justify-between p-4 transition-all duration-200 '
  if (displayError.value) {
    classes += 'border-2 border-om-error bg-om-error/5'
  } else if (isSuccess.value) {
    classes += 'border border-om-green bg-om-green/5'
  } else {
    classes += 'border border-gray-300 bg-white hover:bg-gray-50 hover:border-om-green'
  }
  return classes
})

const iconClass = computed(() =>
  displayError.value
    ? 'text-om-error'
    : isSuccess.value
      ? 'text-om-green'
      : 'text-gray-500',
)

function handleRemove(event: MouseEvent) {
  event.stopPropagation()
  sizeError.value = null
  emit('fileChange', props.field, null)
}

function openPicker() {
  fileInput.value?.click()
}

defineExpose({ openPicker, fileInput })
</script>

<template>
  <div>
    <input
      ref="fileInput"
      type="file"
      class="hidden"
      accept=".pdf,.png,.jpg,.jpeg"
      :multiple="multiple"
      @change="handleFileSelect"
    />

    <div :class="containerClasses" @click="openPicker">
      <div class="flex items-center gap-3">
        <FileText :class="['h-5 w-5 shrink-0', iconClass]" />
        <div>
          <p :class="['text-sm font-medium', hasFile ? 'text-gray-800' : 'text-gray-400']">
            {{ selectedFile ? selectedFile.name : label }}
          </p>

          <p v-if="displayError" class="text-xs font-medium text-om-error">{{ displayError }}</p>
          <p v-else-if="isUploading" class="text-xs text-gray-400">Uploading...</p>
          <p v-else-if="isSuccess" class="text-xs text-gray-400">
            {{ formatFileSize(selectedFile?.size) }}
          </p>
          <p v-else class="text-xs text-gray-400">PDF, PNG or JPG. Max {{ maxSizeMB }} MB</p>
        </div>
      </div>

      <X
        v-if="displayError"
        class="h-5 w-5 shrink-0 text-om-error"
        @click="handleRemove"
      />
      <X
        v-else-if="isUploading"
        class="h-5 w-5 shrink-0 text-gray-500"
        @click="handleRemove"
      />
      <Trash2
        v-else-if="isSuccess"
        class="h-5 w-5 shrink-0 text-gray-500"
        @click="handleRemove"
      />
      <Upload v-else class="h-5 w-5 shrink-0 text-gray-500" />

      <div v-if="isUploading" class="absolute inset-x-0 bottom-0 h-1 bg-gray-100">
        <div
          class="h-full bg-om-green transition-all duration-300"
          :style="{ width: `${uploadProgress}%` }"
        />
      </div>
    </div>
  </div>
</template>
